package com.tlb.tour;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.content.Intent;
import android.net.Uri;
import android.view.Gravity;
import android.widget.*;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.*;
import com.google.firebase.storage.FirebaseStorage;
import com.google.firebase.storage.StorageReference;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;

import java.util.*;
import java.util.regex.*;

public class MainActivity extends Activity {
    private final int BLUE = Color.rgb(25,88,220);
    private final int GREEN = Color.rgb(20,150,90);
    private final int RED = Color.rgb(220,60,60);
    private LinearLayout root;
    private FirebaseAuth auth;
    private FirebaseFirestore db;
    private FirebaseStorage storage;
    private Uri pendingImage;
    private String pendingMatchId = "";

    @Override protected void onCreate(Bundle b) {
        super.onCreate(b);
        auth=FirebaseAuth.getInstance(); db=FirebaseFirestore.getInstance(); storage=FirebaseStorage.getInstance();
        if(auth.getCurrentUser()!=null) showHome(); else showLogin();
    }

    private TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.DKGRAY);t.setPadding(10,12,10,12);return t;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setPadding(14,10,14,10);root.addView(e);return e;}
    private void base(String title){ScrollView sc=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,24);root.setBackgroundColor(Color.rgb(245,248,255));TextView h=tv(title,27);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setTextColor(Color.WHITE);h.setGravity(Gravity.CENTER);h.setBackgroundColor(BLUE);root.addView(h);sc.addView(root);setContentView(sc);}
    private void back(){Button b=btn("← Back");root.addView(b);b.setOnClickListener(v->showHome());}
    private void msg(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

    private void showLogin(){base("👑 TLB TOUR");TextView sub=tv("FREE FIRE TOURNAMENT\nSecure • Fair • Competitive",18);sub.setGravity(Gravity.CENTER);root.addView(sub);EditText e=field("Email");EditText p=field("Password");p.setInputType(129);Button l=btn("🔐 Login");root.addView(l);Button r=btn("📝 Create New Account");root.addView(r);l.setOnClickListener(v->{String a=e.getText().toString().trim(),q=p.getText().toString();if(a.isEmpty()||q.isEmpty()){msg("Email এবং Password দিন");return;}l.setEnabled(false);auth.signInWithEmailAndPassword(a,q).addOnCompleteListener(t->{l.setEnabled(true);if(t.isSuccessful())showHome();else msg(t.getException()!=null?t.getException().getMessage():"Login ব্যর্থ");});});r.setOnClickListener(v->showRegister());}

    private void showRegister(){base("📝 Create Account");EditText n=field("Full Name"),u=field("Username"),e=field("Email"),ph=field("Phone Number"),p=field("Password"),c=field("Confirm Password"),ref=field("Referral Code (Optional)");p.setInputType(129);c.setInputType(129);Button b=btn("✅ Create Account");root.addView(b);Button back=btn("← Back to Login");root.addView(back);b.setOnClickListener(v->{String ns=n.getText().toString().trim(),us=u.getText().toString().trim(),es=e.getText().toString().trim(),ps=p.getText().toString(),cs=c.getText().toString(),rs=ref.getText().toString().trim();if(ns.isEmpty()||us.isEmpty()||es.isEmpty()||ps.isEmpty()){msg("সব প্রয়োজনীয় তথ্য দিন");return;}if(!ps.equals(cs)){msg("Password মিলছে না");return;}if(ps.length()<6){msg("Password কমপক্ষে 6 অক্ষরের হতে হবে");return;}b.setEnabled(false);auth.createUserWithEmailAndPassword(es,ps).addOnCompleteListener(t->{if(!t.isSuccessful()){b.setEnabled(true);msg(t.getException()!=null?t.getException().getMessage():"Account তৈরি হয়নি");return;}String uid=auth.getCurrentUser().getUid();Map<String,Object> m=new HashMap<>();m.put("uid",uid);m.put("name",ns);m.put("username",us);m.put("email",es);m.put("phone",ph.getText().toString().trim());m.put("referralCode","TLB"+uid.substring(0,6).toUpperCase());m.put("referralInput",rs);m.put("walletBalance",0.0);m.put("role","user");m.put("createdAt",System.currentTimeMillis());db.collection("users").document(uid).set(m).addOnCompleteListener(x->{b.setEnabled(true);if(x.isSuccessful()){msg("Account সফলভাবে তৈরি হয়েছে");showHome();}else msg("Profile save হয়নি");});});});back.setOnClickListener(v->showLogin());}

    private void showHome(){base("👑 TLB TOUR");TextView sub=tv("FREE FIRE TOURNAMENT\nLive • Fair • Competitive",18);sub.setGravity(Gravity.CENTER);root.addView(sub);TextView bal=tv("💰 Wallet\nLoading...",21);bal.setTextColor(Color.WHITE);bal.setGravity(Gravity.CENTER);bal.setBackgroundColor(GREEN);root.addView(bal);String[] items={"🏆 Tournaments","🎮 My Matches","📊 Results","📈 Auto Point Table","💰 Wallet","📥 Deposit","📤 Withdraw","🎁 Referral","🔥 Daily Earnings","🔔 Notifications","👤 Profile","⚙️ Admin Panel","🚪 Logout"};for(String s:items){Button b=btn(s);root.addView(b);b.setOnClickListener(v->{if(s.contains("Tournaments"))showTournaments();else if(s.contains("My Matches"))showMyMatches();else if(s.contains("Results"))showResults();else if(s.contains("Point"))showPointTable();else if(s.equals("💰 Wallet"))showWallet();else if(s.contains("Deposit"))showDeposit();else if(s.contains("Withdraw"))showWithdraw();else if(s.contains("Referral"))showReferral();else if(s.contains("Daily"))showLeaderboard();else if(s.contains("Notifications"))showNotifications();else if(s.contains("Profile"))showProfile();else if(s.contains("Admin"))showAdmin();else {auth.signOut();showLogin();}});}loadUserBalance(bal);}
    private void loadUserBalance(TextView bal){if(auth.getCurrentUser()==null)return;db.collection("users").document(auth.getCurrentUser().getUid()).get().addOnSuccessListener(d->{double x=d.getDouble("walletBalance")!=null?d.getDouble("walletBalance"):0;bal.setText(String.format(Locale.US,"💰 Wallet\n৳ %.2f",x));});}

    private void showTournaments(){base("🏆 Tournaments");TextView info=tv("Open tournaments • Join with wallet • Real-time status",15);root.addView(info);db.collection("tournaments").get().addOnSuccessListener(s->{if(s.isEmpty())root.addView(tv("এখনও কোনো tournament publish করা হয়নি।",17));for(DocumentSnapshot d:s.getDocuments()){String id=d.getId(),name=d.getString("name"),status=d.getString("status");double fee=num(d,"entryFee"),prize=num(d,"prize");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(12,12,12,12);TextView t=tv("🏆 "+safe(name)+"\nEntry: ৳"+fee+"   Prize: ৳"+prize+"\nStatus: "+safe(status),17);card.addView(t);Button j=btn("Join Now");card.addView(j);root.addView(card);j.setEnabled(!"CLOSED".equalsIgnoreCase(status));j.setOnClickListener(v->joinTournament(id,name,fee,j));}});back();}
    private void joinTournament(String id,String name,double fee,Button b){String uid=auth.getCurrentUser().getUid();b.setEnabled(false);db.runTransaction(tr->{DocumentReference u=db.collection("users").document(uid),e=db.collection("entries").document(uid+"_"+id);DocumentSnapshot ud=tr.get(u);double bal=num(ud,"walletBalance");if(bal<fee)throw new FirebaseFirestoreException("Wallet balance কম",FirebaseFirestoreException.Code.ABORTED);tr.update(u,"walletBalance",bal-fee);Map<String,Object> m=new HashMap<>();m.put("uid",uid);m.put("tournamentId",id);m.put("tournamentName",name);m.put("entryFee",fee);m.put("status","JOINED");m.put("createdAt",System.currentTimeMillis());tr.set(e,m);return null;}).addOnSuccessListener(x->{msg("Tournament joined");b.setEnabled(false);}).addOnFailureListener(x->{b.setEnabled(true);msg(x.getMessage()!=null?x.getMessage():"Join failed");});}

    private void showMyMatches(){base("🎮 My Matches");db.collection("entries").whereEqualTo("uid",auth.getCurrentUser().getUid()).get().addOnSuccessListener(s->{if(s.isEmpty())root.addView(tv("আপনি এখনো কোনো ম্যাচে join করেননি।",17));for(DocumentSnapshot d:s)root.addView(tv("🎮 "+safe(d.getString("tournamentName"))+"\nEntry: ৳"+num(d,"entryFee")+"\nStatus: "+safe(d.getString("status")),17));});back();}
    private void showResults(){base("📊 Results");db.collection("results").get().addOnSuccessListener(s->{if(s.isEmpty())root.addView(tv("এখনও কোনো result publish হয়নি।",17));for(DocumentSnapshot d:s){root.addView(tv("🏆 "+safe(d.getString("matchId"))+"\nPlayer: "+safe(d.getString("playerName"))+"\nRank: "+num(d,"rank")+"   Kills: "+num(d,"kills")+"   Points: "+num(d,"totalPoints"),17));}});back();}

    private void showWallet(){base("💰 Wallet");TextView b=tv("Loading...",24);b.setGravity(Gravity.CENTER);root.addView(b);loadUserBalance(b);Button h=btn("📜 Transaction History");root.addView(h);h.setOnClickListener(v->showTransactions());back();}
    private void showTransactions(){base("📜 Transactions");db.collection("transactions").whereEqualTo("uid",auth.getCurrentUser().getUid()).get().addOnSuccessListener(s->{if(s.isEmpty())root.addView(tv("কোনো transaction নেই।",17));for(DocumentSnapshot d:s)root.addView(tv(""+safe(d.getString("type"))+" | ৳"+num(d,"amount")+" | "+safe(d.getString("status"))+"\n"+safe(d.getString("method"))+"\n"+safe(d.getString("createdAtText")),16));});back();}

    private void showDeposit(){base("📥 Deposit");TextView x=tv("bKash / Nagad deposit request",17);root.addView(x);Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"bKash","Nagad"}));root.addView(sp);EditText amount=field("Amount (৳)"),trx=field("Transaction ID");Button b=btn("Submit Deposit");root.addView(b);b.setOnClickListener(v->{double a=parse(amount.getText().toString());String tr=trx.getText().toString().trim();if(a<=0||tr.isEmpty()){msg("Amount এবং Transaction ID দিন");return;}Map<String,Object> m=tx("DEPOSIT",a,(String)sp.getSelectedItem());m.put("transactionId",tr);m.put("uid",auth.getCurrentUser().getUid());m.put("status","PENDING");db.collection("transactions").add(m).addOnSuccessListener(d->{msg("Deposit request submitted");showWallet();});});back();}
    private void showWithdraw(){base("📤 Withdraw");Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"bKash","Nagad"}));root.addView(sp);EditText num=field("bKash / Nagad Number"),amount=field("Amount (৳)");Button b=btn("Submit Withdraw");root.addView(b);b.setOnClickListener(v->{double a=parse(amount.getText().toString());String n=num.getText().toString().trim();if(a<=0||n.isEmpty()){msg("সঠিক তথ্য দিন");return;}Map<String,Object> m=tx("WITHDRAW",a,(String)sp.getSelectedItem());m.put("uid",auth.getCurrentUser().getUid());m.put("accountNumber",n);m.put("status","PENDING");db.collection("transactions").add(m).addOnSuccessListener(d->{msg("Withdraw request submitted");showWallet();});});back();}

    private void showReferral(){base("🎁 Referral System");db.collection("users").document(auth.getCurrentUser().getUid()).get().addOnSuccessListener(d->{String c=safe(d.getString("referralCode"));root.addView(tv("Your Referral Code\n"+c,24));root.addView(tv("Share this code with new players. Referral tracking is stored in Firebase.",16));Button cp=btn("📋 Copy Code");root.addView(cp);cp.setOnClickListener(v->{android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);cm.setPrimaryClip(android.content.ClipData.newPlainText("TLB Referral",c));msg("Code copied");});});db.collection("users").whereEqualTo("referralInput",safeReferral()).get().addOnSuccessListener(s->root.addView(tv("Your direct referrals: "+s.size(),18)));back();}
    private String safeReferral(){return "";}

    private void showPointTable(){base("📈 Auto Point Table");root.addView(tv("Points are calculated from published match results. Admin can upload a match screenshot and OCR will prepare the result draft.",15));db.collection("pointTable").get().addOnSuccessListener(s->{ArrayList<DocumentSnapshot>a=new ArrayList<>(s.getDocuments());Collections.sort(a,(x,y)->Double.compare(num(y,"points"),num(x,"points")));int rank=1;for(DocumentSnapshot d:a)root.addView(tv(rank+++". "+safe(d.getString("playerName"))+" — "+num(d,"points")+" pts",17));if(a.isEmpty())root.addView(tv("কোনো point data নেই।",17));});back();}
    private void showLeaderboard(){base("🔥 Daily Earnings Leaderboard");db.collection("leaderboard").get().addOnSuccessListener(s->{ArrayList<DocumentSnapshot>a=new ArrayList<>(s.getDocuments());Collections.sort(a,(x,y)->Double.compare(num(y,"earnings"),num(x,"earnings")));int r=1;for(DocumentSnapshot d:a)root.addView(tv(r+++". "+safe(d.getString("playerName"))+" — ৳"+num(d,"earnings"),17));if(a.isEmpty())root.addView(tv("আজকের leaderboard এখনো তৈরি হয়নি।",17));});back();}
    private void showNotifications(){base("🔔 Notifications");db.collection("notifications").whereEqualTo("userId",auth.getCurrentUser().getUid()).get().addOnSuccessListener(s->{if(s.isEmpty())root.addView(tv("কোনো notification নেই।",17));for(DocumentSnapshot d:s)root.addView(tv("🔔 "+safe(d.getString("title"))+"\n"+safe(d.getString("body")),16));});back();}
    private void showProfile(){base("👤 Profile");db.collection("users").document(auth.getCurrentUser().getUid()).get().addOnSuccessListener(d->{root.addView(tv("Name: "+safe(d.getString("name")),18));root.addView(tv("Username: "+safe(d.getString("username")),18));root.addView(tv("Email: "+safe(d.getString("email")),18));root.addView(tv("Phone: "+safe(d.getString("phone")),18));root.addView(tv("Referral: "+safe(d.getString("referralCode")),18));root.addView(tv("Wallet: ৳"+num(d,"walletBalance"),18));});back();}

    private void showAdmin(){db.collection("users").document(auth.getCurrentUser().getUid()).get().addOnSuccessListener(d->{if(!"admin".equalsIgnoreCase(safe(d.getString("role")))){msg("Admin access required");return;}adminMenu();});}
    private void adminMenu(){base("⚙️ Admin Panel");String[] a={"➕ Create Tournament","📋 Manage Tournaments","🧾 Match Result + Screenshot OCR","💳 Deposit / Withdraw Requests","👥 User Management","🏆 Earnings Leaderboard","🔔 Send Notification"};for(String s:a){Button b=btn(s);root.addView(b);b.setOnClickListener(v->{if(s.contains("Create"))adminCreateTournament();else if(s.contains("Manage"))adminManageTournaments();else if(s.contains("Match Result"))adminResultOCR();else if(s.contains("Deposit"))adminTransactions();else if(s.contains("User"))adminUsers();else if(s.contains("Earnings"))adminLeaderboard();else adminNotification();});}back();}
    private void adminCreateTournament(){base("➕ Create Tournament");EditText n=field("Tournament Name"),fee=field("Entry Fee"),pr=field("Prize Pool"),start=field("Start Time"),max=field("Max Players");Button b=btn("Publish Tournament");root.addView(b);b.setOnClickListener(v->{if(n.getText().toString().trim().isEmpty()){msg("Name দিন");return;}Map<String,Object>m=new HashMap<>();m.put("name",n.getText().toString().trim());m.put("entryFee",parse(fee.getText().toString()));m.put("prize",parse(pr.getText().toString()));m.put("startTime",start.getText().toString().trim());m.put("maxPlayers",(long)parse(max.getText().toString()));m.put("status","OPEN");m.put("createdAt",System.currentTimeMillis());db.collection("tournaments").add(m).addOnSuccessListener(x->{msg("Tournament published");adminMenu();});});back();}
    private void adminManageTournaments(){base("📋 Manage Tournaments");db.collection("tournaments").get().addOnSuccessListener(s->{for(DocumentSnapshot d:s){Button b=btn("❌ Close: "+safe(d.getString("name")));root.addView(b);b.setOnClickListener(v->d.getReference().update("status","CLOSED").addOnSuccessListener(x->{msg("Closed");adminManageTournaments();}));}});back();}

    private void adminTransactions(){base("💳 Deposit / Withdraw");db.collection("transactions").whereEqualTo("status","PENDING").get().addOnSuccessListener(s->{if(s.isEmpty())root.addView(tv("Pending request নেই।",17));for(DocumentSnapshot d:s){String type=safe(d.getString("type"));Button b=btn(type+" ৳"+num(d,"amount")+" • "+safe(d.getString("method")));root.addView(b);b.setOnClickListener(v->approveTransaction(d));}});back();}
    private void approveTransaction(DocumentSnapshot d){String uid=d.getString("uid");double amount=num(d,"amount");String type=safe(d.getString("type"));db.collection("users").document(uid).get().addOnSuccessListener(u->{double bal=num(u,"walletBalance");double newBal=bal+("DEPOSIT".equals(type)?amount:-amount);if("WITHDRAW".equals(type)&&bal<amount){msg("User balance insufficient");return;}u.getReference().update("walletBalance",newBal);d.getReference().update("status","APPROVED","approvedAt",System.currentTimeMillis()).addOnSuccessListener(x->{Map<String,Object>n=new HashMap<>();n.put("userId",uid);n.put("title",type+" approved");n.put("body","Your request of ৳"+amount+" was approved.");n.put("createdAt",System.currentTimeMillis());db.collection("notifications").add(n);msg("Approved");adminTransactions();});});}
    private void adminUsers(){base("👥 User Management");db.collection("users").get().addOnSuccessListener(s->{for(DocumentSnapshot d:s)root.addView(tv(safe(d.getString("username"))+" | "+safe(d.getString("email"))+" | ৳"+num(d,"walletBalance")+" | role="+safe(d.getString("role")),15));});back();}
    private void adminLeaderboard(){base("🏆 Earnings Leaderboard");db.collection("leaderboard").get().addOnSuccessListener(s->{for(DocumentSnapshot d:s)root.addView(tv(safe(d.getString("playerName"))+" — ৳"+num(d,"earnings"),17));});back();}
    private void adminNotification(){base("🔔 Send Notification");EditText uid=field("User UID (blank = all)");EditText title=field("Title"),body=field("Message");Button b=btn("Send");root.addView(b);b.setOnClickListener(v->{String u=uid.getText().toString().trim();Map<String,Object>m=new HashMap<>();m.put("userId",u);m.put("title",title.getText().toString().trim());m.put("body",body.getText().toString().trim());m.put("createdAt",System.currentTimeMillis());db.collection("notifications").add(m).addOnSuccessListener(x->{msg("Notification saved");adminMenu();});});back();}

    private void adminResultOCR(){base("🧾 Match Result + Screenshot OCR");EditText mid=field("Match ID / Tournament Match");Button pick=btn("📷 Select Result Screenshot");root.addView(pick);TextView status=tv("Screenshot দিলে OCR থেকে rank/kills draft তৈরি হবে।",15);root.addView(status);Button save=btn("✅ Save OCR Result");root.addView(save);pick.setOnClickListener(v->{pendingMatchId=mid.getText().toString().trim();save.setEnabled(true);Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,9001);});save.setEnabled(false);save.setOnClickListener(v->saveOCRResult(status));}
    private void saveOCRResult(TextView status){if(pendingImage==null||pendingMatchId.isEmpty()){msg("Match ID এবং screenshot দিন");return;}status.setText("OCR চলছে...");try{InputImage image=InputImage.fromFilePath(this,pendingImage);TextRecognizer r=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);r.process(image).addOnSuccessListener(res->{String raw=res.getText();status.setText("OCR complete. Text: "+raw.substring(0,Math.min(raw.length(),500)));saveParsedResults(pendingMatchId,raw,status);}).addOnFailureListener(e->status.setText("OCR failed: "+e.getMessage()));}catch(Exception e){status.setText("Image read failed: "+e.getMessage());}}
    private void saveParsedResults(String match,String raw,TextView status){List<ResultRow> rows=parseOCR(raw);if(rows.isEmpty()){status.setText(status.getText()+"\nকোনো rank/kills row পাওয়া যায়নি। Screenshot format অনুযায়ী parser আরও tune করতে হবে.");return;}WriteBatch batch=db.batch();for(ResultRow row:rows){DocumentReference ref=db.collection("results").document();Map<String,Object>m=new HashMap<>();m.put("matchId",match);m.put("playerName",row.name);m.put("rank",row.rank);m.put("kills",row.kills);m.put("placementPoints",placementPoints(row.rank));m.put("totalPoints",placementPoints(row.rank)+row.kills);m.put("createdAt",System.currentTimeMillis());batch.set(ref,m);}batch.commit().addOnSuccessListener(x->{rebuildPoints(rows,match);status.setText(status.getText()+"\nSaved "+rows.size()+" result rows. Point table updated.");}).addOnFailureListener(e->status.setText(status.getText()+"\nSave failed: "+e.getMessage()));}
    private List<ResultRow> parseOCR(String raw){ArrayList<ResultRow> out=new ArrayList<>();for(String line:raw.split("\\n")){String z=line.trim().replaceAll("[^A-Za-z0-9_ .-]"," ").replaceAll("\\s+"," ");Matcher m=Pattern.compile("^(\\d{1,2})\\s+(.+?)\\s+(\\d{1,2})\\s*$").matcher(z);if(m.find()){int rank=(int)parse(m.group(1)),kills=(int)parse(m.group(3));if(rank>=1&&rank<=50&&kills>=0&&kills<=50)out.add(new ResultRow(m.group(2).trim(),rank,kills));}}return out;}
    private void rebuildPoints(List<ResultRow>rows,String match){for(ResultRow r:rows){String key=r.name.toLowerCase(Locale.US).replaceAll("[^a-z0-9]","");DocumentReference ref=db.collection("pointTable").document(key);db.runTransaction(t->{DocumentSnapshot d=t.get(ref);double p=d.exists()?num(d,"points"):0;t.set(ref,new HashMap<String,Object>(){{put("playerName",r.name);put("points",p+placementPoints(r.rank)+r.kills);put("lastMatch",match);}},SetOptions.merge());return null;});}}
    private int placementPoints(int rank){int[]p={0,12,9,8,7,6,5,4,3,2,1};return rank>=1&&rank<=10?p[rank]:0;}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==9001&&result==RESULT_OK&&data!=null){pendingImage=data.getData();msg("Screenshot selected. এখন OCR Save চাপুন");}}

    private Map<String,Object> tx(String type,double amount,String method){Map<String,Object>m=new HashMap<>();m.put("type",type);m.put("amount",amount);m.put("method",method);m.put("createdAt",System.currentTimeMillis());m.put("createdAtText",new Date().toString());return m;}
    private double num(DocumentSnapshot d,String k){Number n=d.get(k,Number.class);return n==null?0:n.doubleValue();}
    private double parse(String s){try{return Double.parseDouble(s.trim());}catch(Exception e){return 0;}}
    private String safe(String s){return s==null?"":s;}
    private static class ResultRow{String name;int rank,kills;ResultRow(String n,int r,int k){name=n;rank=r;kills=k;}}
}
