package com.tlb.touradmin;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.Gravity;
import android.widget.*;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.*;
import java.util.*;

public class AdminActivity extends Activity {
    private static final int BG=Color.rgb(5,11,24), PANEL=Color.rgb(10,31,61), CYAN=Color.rgb(22,185,255), PINK=Color.rgb(255,80,130), WHITE=Color.WHITE, MUTED=Color.rgb(180,195,215);
    private LinearLayout root; private FirebaseAuth auth; private FirebaseFirestore db;
    @Override protected void onCreate(Bundle b){super.onCreate(b); FirebaseApp.initializeApp(this); auth=FirebaseAuth.getInstance(); db=FirebaseFirestore.getInstance(); if(auth.getCurrentUser()!=null)verifyAdmin(); else login();}
    private TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(WHITE);t.setPadding(16,14,16,14);return t;}
    private EditText field(String h){EditText e=new EditText(this);e.setHint(h);e.setTextColor(WHITE);e.setHintTextColor(MUTED);e.setPadding(18,10,18,10);root.addView(e);return e;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(WHITE);b.setBackground(bg(PANEL,18));return b;}
    private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);g.setStroke(1,CYAN);return g;}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,14,18,14);c.setBackground(bg(PANEL,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,8,0,8);c.setLayoutParams(p);return c;}
    private void base(String title){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(14,14,14,30);root.setBackgroundColor(BG);TextView h=tv("⚙️  "+title,24);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setGravity(Gravity.CENTER);h.setBackground(bg(Color.rgb(7,31,67),28));root.addView(h);s.addView(root);setContentView(s);}
    private void login(){base("TLB TOUR ADMIN");TextView x=tv("ADMIN LOGIN\nSeparate Admin App",20);x.setGravity(Gravity.CENTER);x.setTextColor(CYAN);root.addView(x);EditText u=field("Admin Username");EditText p=field("6-digit Password");p.setInputType(2|16);Button b=btn("🔐  ADMIN LOGIN");root.addView(b);b.setOnClickListener(v->{String us=u.getText().toString().trim().toLowerCase(Locale.US),pw=p.getText().toString();if(us.isEmpty()||!pw.matches("\\d{6}")){toast("Username ও 6-digit password দিন");return;}String email=us.replaceAll("[^a-z0-9._-]","_")+"@tlbtour.app";b.setEnabled(false);auth.signInWithEmailAndPassword(email,pw).addOnCompleteListener(t->{b.setEnabled(true);if(t.isSuccessful())verifyAdmin();else toast("Admin login failed");});});}
    private void verifyAdmin(){String uid=auth.getCurrentUser().getUid();db.collection("users").document(uid).get().addOnSuccessListener(d->{if("admin".equalsIgnoreCase(s(d.getString("role"))))dashboard();else{auth.signOut();toast("This account is not an admin");login();}}).addOnFailureListener(e->{auth.signOut();login();});}
    private void dashboard(){base("ADMIN DASHBOARD");TextView h=tv("TLB TOUR\nControl Center",26);h.setGravity(Gravity.CENTER);h.setTextColor(CYAN);root.addView(h);String[][] a={{"🏆","Manage Tournaments"},{"➕","Create Tournament"},{"💳","Deposit / Withdraw"},{"👥","User Management"},{"🧾","Match Results"},{"📈","Point Table"},{"🏅","Earnings Leaderboard"},{"🔔","Notifications"}};for(String[] q:a){Button b=btn(q[0]+"  "+q[1]);root.addView(b);b.setOnClickListener(v->{String z=q[1];if(z.startsWith("Manage"))manage();else if(z.startsWith("Create"))create();else if(z.startsWith("Deposit"))transactions();else if(z.startsWith("User"))users();else if(z.startsWith("Match"))results();else if(z.startsWith("Point"))points();else if(z.startsWith("Earnings"))leaderboard();else notifyPage();});}Button out=btn("↪ Logout");root.addView(out);out.setOnClickListener(v->{auth.signOut();login();});}
    private void create(){base("CREATE TOURNAMENT");EditText n=field("Tournament Name"),mode=field("Mode e.g. BR / CS / Lone Wolf"),map=field("Map"),fee=field("Entry Fee"),pr=field("Prize Pool"),start=field("Start Time"),max=field("Max Players");Button b=btn("🚀 PUBLISH TOURNAMENT");root.addView(b);b.setOnClickListener(v->{Map<String,Object>m=new HashMap<>();m.put("name",n.getText().toString().trim());m.put("mode",mode.getText().toString().trim());m.put("map",map.getText().toString().trim());m.put("entryFee",num(fee.getText().toString()));m.put("prize",num(pr.getText().toString()));m.put("startTime",start.getText().toString().trim());m.put("maxPlayers",(long)num(max.getText().toString()));m.put("joinedPlayers",0L);m.put("status","OPEN");m.put("createdAt",System.currentTimeMillis());db.collection("tournaments").add(m).addOnSuccessListener(x->{toast("Tournament published");dashboard();});});back();}
    private void manage(){base("MANAGE TOURNAMENTS");db.collection("tournaments").get().addOnSuccessListener(s->{for(DocumentSnapshot d:s){LinearLayout c=card();c.addView(tv("🔥 "+s(d.getString("name"))+"\nMode: "+s(d.getString("mode"))+"\nStatus: "+s(d.getString("status"))+"\nPlayers: "+num(d,"joinedPlayers")+" / "+num(d,"maxPlayers"),16));Button b=btn("CLOSE / FINISH");c.addView(b);root.addView(c);b.setOnClickListener(v->d.getReference().update("status","CLOSED").addOnSuccessListener(x->{toast("Updated");manage();}));}});back();}
    private void transactions(){base("DEPOSIT / WITHDRAW REQUESTS");db.collection("transactions").whereEqualTo("status","PENDING").get().addOnSuccessListener(s->{if(s.isEmpty())root.addView(tv("No pending requests.",17));for(DocumentSnapshot d:s){LinearLayout c=card();c.addView(tv(s(d.getString("type"))+"  ৳"+num(d,"amount")+"\nMethod: "+s(d.getString("method"))+"\nUID: "+s(d.getString("uid")),15));Button ap=btn("✅ APPROVE");Button rj=btn("❌ REJECT");c.addView(ap);c.addView(rj);root.addView(c);ap.setOnClickListener(v->approve(d,true));rj.setOnClickListener(v->approve(d,false));}});back();}
    private void approve(DocumentSnapshot d,boolean yes){String uid=s(d.getString("uid"));double a=num(d,"amount");String type=s(d.getString("type"));if(!yes){d.getReference().update("status","REJECTED").addOnSuccessListener(x->transactions());return;}db.collection("users").document(uid).get().addOnSuccessListener(u->{double bal=num(u,"walletBalance");if("WITHDRAW".equals(type)&&bal<a){toast("Insufficient wallet balance");return;}double nb=bal+("DEPOSIT".equals(type)?a:-a);u.getReference().update("walletBalance",nb).addOnSuccessListener(x->d.getReference().update("status","APPROVED","approvedAt",System.currentTimeMillis()).addOnSuccessListener(y->transactions()));});}
    private void users(){base("USER MANAGEMENT");db.collection("users").get().addOnSuccessListener(s->{for(DocumentSnapshot d:s)root.addView(tv("👤 "+s(d.getString("username"))+"\nName: "+s(d.getString("name"))+"\nPhone: "+s(d.getString("phone"))+"\nWallet: ৳"+num(d,"walletBalance")+"\nRole: "+s(d.getString("role")),15));});back();}
    private void results(){base("MATCH RESULTS");EditText mid=field("Match ID"),player=field("Player Name"),rank=field("Rank"),kills=field("Kills");Button b=btn("💾 SAVE RESULT");root.addView(b);b.setOnClickListener(v->{int r=(int)num(rank.getText().toString()),k=(int)num(kills.getText().toString());Map<String,Object>m=new HashMap<>();m.put("matchId",mid.getText().toString().trim());m.put("playerName",player.getText().toString().trim());m.put("rank",r);m.put("kills",k);m.put("placementPoints",placement(r));m.put("totalPoints",placement(r)+k);m.put("createdAt",System.currentTimeMillis());db.collection("results").add(m).addOnSuccessListener(x->{String key=player.getText().toString().trim().toLowerCase(Locale.US).replaceAll("[^a-z0-9]","");DocumentReference p=db.collection("pointTable").document(key);p.set(new HashMap<String,Object>(){{put("playerName",player.getText().toString().trim());put("points",FieldValue.increment(placement(r)+k));}},SetOptions.merge()).addOnSuccessListener(y->{toast("Result saved");dashboard();});});});back();}
    private void points(){base("AUTO POINT TABLE");db.collection("pointTable").get().addOnSuccessListener(s->{ArrayList<DocumentSnapshot>a=new ArrayList<>(s.getDocuments());a.sort((x,y)->Double.compare(num(y,"points"),num(x,"points")));int r=1;for(DocumentSnapshot d:a)root.addView(tv(r+++". "+s(d.getString("playerName"))+" — "+num(d,"points")+" pts",17));});back();}
    private void leaderboard(){base("EARNINGS LEADERBOARD");db.collection("leaderboard").get().addOnSuccessListener(s->{for(DocumentSnapshot d:s)root.addView(tv("🏅 "+s(d.getString("playerName"))+" — ৳"+num(d,"earnings"),17));});back();}
    private void notifyPage(){base("SEND NOTIFICATION");EditText uid=field("User UID (blank = all)"),title=field("Title"),body=field("Message");Button b=btn("📢 SEND NOTIFICATION");root.addView(b);b.setOnClickListener(v->{Map<String,Object>m=new HashMap<>();m.put("userId",uid.getText().toString().trim());m.put("title",title.getText().toString().trim());m.put("body",body.getText().toString().trim());m.put("createdAt",System.currentTimeMillis());db.collection("notifications").add(m).addOnSuccessListener(x->{toast("Notification sent");dashboard();});});back();}
    private void back(){Button b=btn("‹ Back");root.addView(b);b.setOnClickListener(v->dashboard());}
    private String s(String x){return x==null?"":x;} private double num(DocumentSnapshot d,String k){Number n=d.get(k,Number.class);return n==null?0:n.doubleValue();} private double num(String x){try{return Double.parseDouble(x.trim());}catch(Exception e){return 0;}} private int placement(int r){int[]p={0,12,9,8,7,6,5,4,3,2,1};return r>=1&&r<=10?p[r]:0;} private void toast(String x){Toast.makeText(this,x,Toast.LENGTH_SHORT).show();}
}
